### ISSUE TITLE
Jack interface not working as expected

### ISSUE THREAD

**Issue by paketecuento** [motiejus/SoundPatty#10]
If you try the file mode as explained in https://github.com/Motiejus/SoundPatty#usage, SoundPatty works as expected. But if you run SoundPatty with jack driver, It doesn't work :(. SoundPatty simply is not able to detect any match.

**Example:**
console1 --> `mplayer -ao jack:name=mp catch_me.wav`
console2  --> `./soundpatty -a capture -c config.cfg -s samplefile.txt -d jack mp:out_0`

it only works after second attempt with mplayer (without exiting existing SoundPatty instance) and when console2 is

 `./soundpatty -a capture -c config.cfg -s samplefile.txt -d jack -m`

**Comment by motiejus** [comment]
Sorry for a very late response.

The latest changes I did were with files only; and I think I might have messed up the Jack interface somehow.

Since the project is no longer maintained (see README), I will not attempt to find/fix the problem, but would link to a better fork if one comes up.

Sorry I wasn't be of much help.
